### ISSUE TITLE
Support `autopilot/serviceable`

### ISSUE THREAD

**Issue by hbeni** [reiszner/KAP140#3]
I think, currently the `autopilot/kap140/serviceable` is jut checked during system startup.
The standard `autopilot/serviceable` (which is hooked up by the default fgdata failure manager / standard failures gui) seems to not be honored at all.

In the C182S i solved this by adjusting the electrical system which just cuts off the power source.
However, maybe there are better options.
At least it would be cool if the KAP140 implementation would react self-contained to the default servicealbe-property.
Maybe it could just be treaten like power disconnect, or maybe we have a more advanced handling idea (make it inop just like the boot sequence does?)

**Comment by reiszner** [comment]
Yes, will look into it. Should be simple.
Power lost and unservicable are two different things.
BTW, there is also the property 'programmed', if this is false at start time, the AP goes ina fault state and can not be used.
Maybe you want this also in the failure manager.
After boot up it has no effect. At pre flight test the AP check the ROM and is it okay it copy the values in the RAM.
So a faulty ROM does not effect the device while running, only on boot time.

**Comment by hbeni** [comment]
I know that "powered" and "unserviceable" are distinct things, however the failure manager is there to fail stuff in mid-flight, so it should happen something, when triggered :)
I thought of `serviceable` more on a general faulty thing.
Can't the autopilot fail generally?

**Comment by hbeni** [comment]
But it's okay not to implement - it's handled like this on the c182s for years and i think it is fine.

**Comment by reiszner** [comment]
update pushed.
if serviceable becomes 'false', the AP immediatelly goes off
