### ISSUE TITLE
Make the buttons more readable

### ISSUE THREAD

**Issue by hbeni** [reiszner/KAP140#4]
Right now the button labels are rather small and faint. In the C182S i cannot read them easily.
It woul be good if you remapped the UV so the labels are a little bigger; the other option is to edit the texture.

**Comment by reiszner** [comment]
I have it compared with the other devices in the cockpit at it seams the same (maybe the test is not full black).
What me disturb more is the default view focus in the aircraft. It is 75 or 80.
I set it to 60-65, so i can also better read the buttons. But i think the focus is a personal taste.
In the Resources directory you find also the xcf file. You can adjust it to your needs.
(i'm horrible if it comes to texturing … i think i need more time for the texture as for the model)

If i have time i will test something with the display. But as i said above, i'm a noob so dont expect graphical things in the next weeks.

**Comment by hbeni** [comment]
okay, i will look at it

**Comment by hbeni** [comment]
I made it: https://github.com/HHS81/c182s/pull/379/commits/841f644138438b72b96a118b726edb3e55e525dd

I think it would be good to have various versions here in the base repo, so the actual aircraft dev can choose the texture he likes most.
What do you think?


Current:
![Screenshot_20210202_000055](https://user-images.githubusercontent.com/13608602/106532254-1f994880-64f0-11eb-8ff5-d094367a9baf.png)

New:
![Screenshot_20210202_000549](https://user-images.githubusercontent.com/13608602/106532246-1d36ee80-64f0-11eb-89be-4c75d53bc57a.png)

**Comment by reiszner** [comment]
Yea, looks good … i was first exposed that my text isnt black, but insteed its a little bit too thin.
Yes, we should hold more textures in the repo. My original is the bright one.

pushed, thx
