### ISSUE TITLE
More conditions highlight "P" pitch axis failure annunciator, and "R" annunciator

### ISSUE THREAD

**Issue by hbeni** [reiszner/KAP140#7]
- [x] P is on in abnormal G-conditions (`autopilot/kap140/sensors/excess-g` is true)
  (Note that the AP will disconnect here which is already imeplemented)
- [x] P is on at power-on for approximately 30s and may be still on after completing the PFT-tests
   (Note that AP turning on should not be possible as long as the P is on -> pitch axis fail)
- [x] R should be highlighting at the PFT-Step that tests all display elements (no source for that, but it surely should light to be able to see that the light is operational)

Source: Bendix manual, P. 8:
![grafik](https://user-images.githubusercontent.com/13608602/107030013-3ec5fd80-67b0-11eb-9c7e-63a0956b9ef7.png)

----
Additional sources:

**1. P is on in abnormal G-conditions**:
C182S PO, p. S15-8:
![grafik](https://user-images.githubusercontent.com/13608602/107029328-230e2780-67af-11eb-8a71-cc7460bdda9f.png)

S15-18:
![grafik](https://user-images.githubusercontent.com/13608602/107029538-74b6b200-67af-11eb-8348-97c88eb85cc3.png)

----

**2. P is on at power-on until end of preflight tests**:
Note the small wording deviation from the bendix manual /which says that the light _may_ be on _after_ PFT tests.
I conclude that the light turns on at power application and _may_ stay on for a time duration that takes longer than the PFT-tests to complete.

S15-20:
![grafik](https://user-images.githubusercontent.com/13608602/107029595-91eb8080-67af-11eb-88a5-35f189e5ba9d.png)

**Comment by reiszner** [comment]
Yes, i have modelled the annunciator but havn't any idea for conditions to trigger it. Therefor i leave that out.

The property `/autopilot/kap140/sensors/excess-g` is not from my self.
But its simple to trigger ap-disc if one of the axis fail.
This annunciators should also be lit up if the control force overcome the servo force.
But i dont know how strong the servos are and also how to calculate the surface force (aileron or elevator).

At power up the AP checks the servo, thats why the annunciator lit up.
I have no clue why the P-annun lit so long, but maybe because the ailerons are in equilibrium (servo need less force to check, only overcome some friction) and the elevator will pulled down from the gravity (servo need stronger force).

Will be nice if we have actual forces on the surface and trigger a fail if it overcome a threshold.
But this forces should come from the aircraft itself because every aircraft is different.
What i can do on AP side is a check if the surface force exceed the threshold (how strong?).

**Comment by hbeni** [comment]
> The property `/autopilot/kap140/sensors/excess-g` is not from my self.
> But its simple to trigger ap-disc if one of the axis fail.

It’s my work you already integrated :)
What is open is just the animation condition in kap140.xml.

> At power up the AP checks the servo, thats why the annunciator lit up.
I have no clue why the P-annun lit so long,

i think we may do it cheap here and just turn on the Light for 30s at systems bootup...



> What i can do on AP side is a check if the surface force exceed the threshold (how strong?).

That would be nice. We could just add another property in the config for that?

**Comment by reiszner** [comment]
> It’s my work you already integrated :)
> What is open is just the animation condition in kap140.xml.

Have only copied over to not destroy anything, but have now a short look on it.
Dont know who feed this prop, but its okay.
 
> i think we may do it cheap here and just turn on the Light for 30s at systems bootup...

Have it already but i search for a bit randomness.
I think i have seen it somewhere but cant find it again.
But i can also build up a randomness out of `/sim/time/elapsed-sec` with a bit math.
 
> That would be nice. We could just add another property in the config for that?

New properties:
/autopilot/kap140/servo/roll-servo/force
/autopilot/kap140/servo/pitch-servo/force

I think we should include it in the set file to initialize it as 'double' with value 0.
The filters check it with <abs>, so it doesnt matter if the value become negative.
If there is no filter to feed this props, they will stay on 0 and the threshold will never be reached (never failed).

**Comment by hbeni** [comment]
> Dont know who feed this prop, but its okay.

It is fed by the standard pilot-g-damped prop.



> Have it already but i search for a bit randomness.
> I think i have seen it somewhere but cant find it again.

James Turner implemented such a property recently for my cockpit shaking code, look at fgdata g-forces xml.

**Comment by reiszner** [comment]
Yes, have allready found your thread in the mailing list about cockpit shaking.
But thats brand new so it will not work on 2020.3.x.

BTW: i found a ticket (2497) about cone-of-silence.
I have implemented the cone-of-confusion last year on the Citation II (aircraft side).
Maybe this gives you some ideas.

**Comment by hbeni** [comment]
> I have implemented the cone-of-confusion last year on the Citation II (aircraft side).

Thanks for the hint, but i really do think this should be handled at the sim side.

**Comment by reiszner** [comment]
Yes right but i need it in a rush because the FD of the Citation II has a sens for the COC to not swing/oscillate at station transit.
If the new code give me all parameters that i need, i can update the FD.

**Comment by reiszner** [comment]
Update pushed.
Please check if its work for you.

**Comment by hbeni** [comment]
will do!

**Comment by hbeni** [comment]
Looks very good already, points found:

- Over-G does not light the "P" annunciator, but should
- the over-G should also cause the P-light when the AP is disconnected

**Comment by reiszner** [comment]
`autopilot/kap140/sensors/excess-g` added to pitch fail conditions.
fixed.
